on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - run: which pulumi
      
      - run: pulumi --version
      
      - run: yarn install
      
      - name: Create local stack
        run: |
          pulumi login --local
          pulumi stack init dev
        env:
          PULUMI_CONFIG_PASSPHRASE: not-a-secret
      
      - uses: pulumi/actions@v3
        env:
          PULUMI_CONFIG_PASSPHRASE: not-a-secret
        with:
          command: preview
          cloud-url: file://~
          stack-name: dev
          
      - run: pulumi --version
